name: flutter_clearmind_archetype_shared
description: "shared"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # android only
  android_id: ^0.3.6
  async: 2.11.0
  dartx: ^1.2.0
  decimal: ^2.3.3
  device_info_plus: ^9.1.2
  # android/ios/macos only
  flutter_cache_manager: ^3.3.1
  # web not
#  flutter_udid: 2.0.1
  uuid: ^4.3.3
  injectable: 2.3.5
  intl: ^0.18.0
  mime: ^1.0.5
  package_info_plus: ^5.0.1
  # web not
  path_provider: ^2.1.2
  rxdart: 0.27.7
  timezone: ^0.9.2
  url_launcher: ^6.2.5
dev_dependencies:

  build_runner: ^2.4.8
  # web not
  custom_lint: ^0.6.2
  
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  logging: ^1.2.0
  mocktail: ^1.0.3

flutter:

