name: flutter_clearmind_archetype_app
description: "app"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clearmind_archetype_shared:
    path: ../shared
  flutter_clearmind_archetype_resource:
    path: ../resource
  flutter_clearmind_archetype_domain:
    path: ../domain
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  injectable: 2.3.5

dev_dependencies:
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
flutter:

