name: flutter_clearmind_archetype_resource
description: "resource"
version: 0.0.1
homepage:

#dependency_overrides:
#  analyzer: 6.2.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.18.1
  intl_utils: 2.8.3
  multiple_localization: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

flutter_intl:
  enabled: false
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n
