name: flutter_clearmind_archetype_resource
description: "resource"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0 <4.0.0"
#dependency_overrides:
#  analyzer: 6.2.0


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  intl_utils: ^2.8.7
  multiple_localization: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:

flutter_intl:
  enabled: false
  main_locale: en
  output_dir: lib/src/generated
  arb_dir: lib/src/l10n
