name: flutter_clearmind_archetype_domain
description: "domain"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clearmind_archetype_resource:
    path: ../resource
  flutter_clearmind_archetype_shared:
    path: ../shared
  async: 2.11.0
  dartx: ^1.2.0
  get_it: ^7.6.7
  injectable: 2.3.5
  meta: ^1.11.0
  tuple: 2.0.2
  rxdart: 0.27.7

dev_dependencies:
  custom_lint: ^0.6.2
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  logging: ^1.2.0
  mocktail: ^1.0.3
flutter:


